= Overview

This guide is designed to help embedded software developers who are already familiar with C to learn the {cpp} features that are particularly useful in embedded systems. It assumes you have intermediate to advanced knowledge of C.

There are a few MISC topics that will make reading this guide more helpful.

== Declaration, Definition, Initialization
In both C and {cpp} functions, types, and variables have a concept of being declared then possibly later defined or initialized. Sometimes, both the declaration and definition/initialization happen in the same step. Sometimes, they occur separately. Pay close attention to the language used, particularly declaration and definition.

[source,c++]
----
int foo(int x);             // function declaration
int globalVariable = 10;    // variable declaration & initialization

int foo(int x) {            // function definition
    int y;                  // variable declaration
    y = x * 10;             // variable initialization
    return y;
}

static void bar(int x) {    // function declaration & definition
    return x + 10;
}

struct s;                   // type declaration
struct s {                  // type definition
    int data;
};
----

== Scope
Variables, functions, types all have an associated scope. Generally, you get a new scope when you use `{}`

[source,c++]
----
int fileScopeGlobal = 100;

static void fileScopeFunction() {
    int functionScopeA = 50;
    for( int i = 0; i < fileScopeA; ++i ) {
        // i only lives within the scope of this for loop
    }
}

struct MyType {
    // this variable only exists for MyType
    inline static int value = 500; // between {} for MyType definition
};

MyType::value; // specify the scope with MyType::
----

== Optimization and Undefined behavior
In both C and {cpp}, the compiler assumes that your code does not contain undefined behavior (UB). This assumption allows compilers to perform extensive optimizations. Since UB enables architecture-specific optimizations for performance and code size, writing correct and readable code is crucial for long-term maintenance. It is more beneficial to prioritize code clarity over obscure optimizations that may seem efficient but can be harder to maintain.

.Example
[source,c++]
----
uint32_t myValue = 0x02;
if( (myValue & (0x1 | 0x2)) == (0x1 | 0x2) ) {
    // both happened
}
else if( myValue & 0x1 ) {
    // left
}
else if( myValue & 0x2 ) {
    // right
}

// vs

bool leftButtonPressed = myValue & 0x01;
bool rightButtonPressed = myValue & 0x02;
if( leftButtonPressed && rightButtonPressed ) {
    // read the line above like a sentence
}
else if( leftButtonPressed ) {
    // read the line above like a sentence
}
else if( rightButtonPressed ) {
    // read the line above like a sentence
}
----

In both code examples, no undefined behavior is present. This allows the compiler to apply optimizations confidently. In the second example, where two boolean variables are used to capture the results of bitwise operations, the compiler is likely to optimize away these variables. This is because the compiler recognizes that the boolean variables are derived from the same myValue and that the bitwise operations are performed in a predictable manner. Consequently, the compiler may generate similar or even identical machine code for both examples, depending on the optimization level and the compiler's ability to perform constant folding and other optimizations.

=== -O0
Even compiling with "no" optimizations, the compiler may still do some basic optimizations, such as the low-hanging fruit cases of, basic arithmetic simplifications, dead code elimination, constant folding, inlining of simple functions, and basic common subexpression elimination.
