= Empty Parameter List

[source,c++,indent=0]
----
void foo(void);
void bar();
----

== TL;DR
Use `()` over `(void)` for function declarations with zero arguments.

== C
* `void foo(void);` explicitly declares a function that takes no arguments.
* `void bar();` leaves the parameter list unspecified in the declaration. The actual number and types of arguments are determined by the function's definition. It is up to the programmer to call the function with the correct number and types of arguments.
* `void bar();` does **not** have a variable number of arguments; the number of arguments is fixed in the function definition but unspecified in the declaration.

== {cpp}
* `void foo(void);` explicitly declares a function that takes no arguments
* `void bar();` explicitly declares a function that takes no arguments

== History
In early versions of C, pre-C89, `void bar();` was the only way to declare a function, leaving the parameters unspecified. When C adopted function prototypes from {cpp}, the need for backward compatibility led to the creation of `void foo(void);` to explicitly indicate that a function takes no arguments. {cpp} continued to support both styles, with `void foo(void);` used primarily for compatibility with C.