= MISC.
:toc:

This section covers key topics that provide foundational knowledge before exploring differences between C and {cpp}. Understanding these fundamentals is crucial for effectively navigating the rest of the guide.


== Declaration, Definition, Initialization
Functions, types, and variables in both C and {cpp} can be declared, defined, or initialized. These processes might occur simultaneously or separately.

Understanding the precise terminology—declarations and definitions—is crucial, as they are not interchangeable.

[source,c++]
----
int foo( int x );           // function declaration
int globalVariable = 10;    // variable declaration & initialization

int foo( int x ) {          // function definition
    int y;                  // variable declaration
    y = x * 10;             // variable initialization
    return y;
}

static void bar( int x ) {  // function declaration & definition
    return x + 10;
}

struct s;                   // type declaration
struct s {                  // type definition
    int data;
};
----

== Scope
Scope refers to the visibility and lifetime of variables, functions, and types. Typically, a new scope is introduced with `{}`, such as in functions, if statements, loops, and other blocks of code. Tightening the scope of variables, functions, and types reduces their exposure and enhances encapsulation.

You can create new scopes by using `{}`:

[source,c++]
----
int fileScopeGlobal = 100;

static void fileScopeFunction() {
    int functionScope = 50;
    for( int loopScope = 0; loopScope < functionScope; ++loopScope ) {
        // 'loopScope' only lives within the scope of this for loop
    }
    {
        int newScope = functionScope + globalScope;
        // newScope only exists within this inner block
    }
    // newScope no longer exists
}

struct MyType {
    // This variable only exists within MyType
    inline static int value = 500; // within {} for MyType definition
};

MyType::value; // Specify the scope with MyType::
----

=== Variable Lifetimes
Scope controls stack variable lifetimes. When an object is created, resources are allocated (e.g., memory), and when the object's lifetime ends (goes out of scope), resources are freed. This behavior is central to the {cpp} principle of Resource Acquisition Is Initialization (RAII), which ensures effective resource management.

== Optimization and Undefined Behavior

=== TL;DR
Use `-Os` or other optimization levels confidently, provided your code avoids undefined behavior. The compiler will not discard any logic.

=== Explanation
Compilers assume code does not contain undefined behavior (UB), allowing them to perform extensive optimizations. UB remains undefined because standards aim to be implementation-agnostic. For instance, while `int` might be 32 bits on many platforms, it's not universally guaranteed. Therefore, casting `int32_t*` to `int*` is undefined behavior, as `int` and `int32_t` are not necessarily the same.

When writing code, it's often tempting to optimize for performance by minimizing operations. However, modern compilers are highly adept at optimizing code, often better than manual optimizations. As long as your code avoids undefined behavior, the compiler handles optimizations efficiently. Adding extra variables for clarity, such as boolean flags, generally does not impact performance at higher optimization levels (-O1, -O2, -O3, -Os). The compiler is likely to generate similar or identical machine code whether you use compact bitwise operations or more readable boolean expressions.

.Example
[source,c++]
----
uint32_t myValue = 0x02;
if( (myValue & (0x1 | 0x2)) == (0x1 | 0x2) ) {
    // both happened
}
else if( myValue & 0x1 ) {
    // left
}
else if( myValue & 0x2 ) {
    // right
}

// vs

bool leftButtonPressed = myValue & 0x01;
bool rightButtonPressed = myValue & 0x02;
if( leftButtonPressed && rightButtonPressed ) {
    // Read the line above like a sentence
}
else if( leftButtonPressed ) {
    // Read the line above like a sentence
}
else if( rightButtonPressed ) {
    // Read the line above like a sentence
}
----

Both examples avoid undefined behavior, allowing the compiler to optimize confidently. In the second example, boolean variables capture the results of bitwise operations, which may lead the compiler to optimize away these variables due to straightforward operations. Thus, the generated machine code may be similar or identical.
