= MISC.
:toc:

This section covers key topics that provide foundational knowledge before exploring differences between C and {cpp}. Understanding these fundamentals is crucial for effectively navigating the rest of the guide.

== Not Your Fathers {cpp}
{cpp} was originally referred to as "C with Classes" from 1979-1982. This early version of {cpp}, akin to pre-standard C, is now outdated. {cpp}03, similar to C89, appears outdated compared to modern standards, but you may still encounter it in legacy code bases. {cpp}11, comparable to C99, represents a significant evolution, one may argue it's the version "1.0" of these languages. Recent updates like C23 and {cpp}23 reflect further advancements.

=== C Standards
* *C99*: Introduced enhancements such as new data types (e.g., long long int), flexible array members, and variable-length arrays.
* *C11*: Added improvements like multithreading support, atomic operations, and enhanced standard library functions.
* *C23*: The latest standard, offering improvements in type-generic programming, enhanced standard library functions, and more. Support is growing, especially with leading compilers like GCC.

=== {cpp} Standards
* *{cpp}03*: The first major update after {cpp}98, adding minor improvements and bug fixes. Still in use on legacy systems but considered outdated.
* *{cpp}11*: Introduced features like auto type deduction, lambda expressions, smart pointers, and concurrency support. Most modern embedded toolchains support {cpp}11.
* *{cpp}14 and {cpp}17*: Provided further refinements and enhancements.
* *{cpp}20*: Added concepts, ranges, calendar and time zone libraries, and other features enhancing expressiveness and safety.
* *{cpp}23*: The latest standard, feature improvements for constexpr and consteval, as well as additions to the standard library, like std::expected. Support from major compilers is beginning to emerge.

=== Support for Modern Standards
As of this writing:

* *GCC*: Version 11 fully supports {cpp}20. Version 12 has partial {cpp}23 support. Version 13 has extensive {cpp}23 support. GCC supports practically any ARM or RISC-V CPU you would want to use. This includes SoftCore's on an FPGA, like the MicroBlaze and Nios II cores, as well as 'hard' ARM/RISC-V cores in an SoC.
* *ARM Compiler (Arm Keil MDK)*: Arm Compiler 6.x supports {cpp}14 and some {cpp}17 features.
* *IAR Embedded Workbench*: Supports {cpp}11 and some features of {cpp}14, with incremental improvements for some {cpp}17 features.

This guide focuses on modern {cpp} ({cpp}11 and above) for the embedded systems industry, particularly for ARM/RISC-V microcontrollers, as major compilers support at least {cpp}11.

== Declaration, Definition, Initialization
Functions, types, and variables in both C and {cpp} can be declared, defined, or initialized. These processes might occur simultaneously or separately.

Understanding the precise terminology—declarations and definitions—is crucial, as they are not interchangeable.

[source,c++]
----
int foo( int x );           // function declaration
int globalVariable = 10;    // variable declaration & initialization

int foo( int x ) {          // function definition
    int y;                  // variable declaration
    y = x * 10;             // variable initialization
    return y;
}

static void bar( int x ) {  // function declaration & definition
    return x + 10;
}

struct s;                   // type declaration
struct s {                  // type definition
    int data;
};
----

== Scope
Scope refers to the visibility and lifetime of variables, functions, and types. Typically, a new scope is introduced with `{}`, such as in functions, if statements, loops, and other blocks of code. Tightening the scope of variables, functions, and types reduces their exposure and enhances encapsulation.

You can create new scopes by using `{}`:

[source,c++]
----
int fileScopeGlobal = 100;

static void fileScopeFunction() {
    int functionScope = 50;
    for( int loopScope = 0; loopScope < functionScope; ++loopScope ) {
        // 'loopScope' only lives within the scope of this for loop
    }
    {
        int newScope = functionScope + globalScope;
        // newScope only exists within this inner block
    }
    // newScope no longer exists
}

struct MyType {
    // This variable only exists within MyType
    inline static int value = 500; // within {} for MyType definition
};

MyType::value; // Specify the scope with MyType::
----

=== Variable Lifetimes
Scope controls stack variable lifetimes. When an object is created, resources are allocated (e.g., memory), and when the object's lifetime ends (goes out of scope), resources are freed. This behavior is central to the {cpp} principle of Resource Acquisition Is Initialization (RAII), which ensures effective resource management.

== Optimization and Undefined Behavior

=== TL;DR
Use `-Os` or other optimization levels confidently, provided your code avoids undefined behavior. The compiler will not discard any logic.

=== Explanation
Compilers assume code does not contain undefined behavior (UB), allowing them to perform extensive optimizations. UB remains undefined because standards aim to be implementation-agnostic. For instance, while `int` might be 32 bits on many platforms, it's not universally guaranteed. Therefore, casting `int32_t*` to `int*` is undefined behavior, as `int` and `int32_t` are not necessarily the same.

When writing code, it's often tempting to optimize for performance by minimizing operations. However, modern compilers are highly adept at optimizing code, often better than manual optimizations. As long as your code avoids undefined behavior, the compiler handles optimizations efficiently. Adding extra variables for clarity, such as boolean flags, generally does not impact performance at higher optimization levels (-O1, -O2, -O3, -Os). The compiler is likely to generate similar or identical machine code whether you use compact bitwise operations or more readable boolean expressions.

.Example
[source,c++]
----
uint32_t myValue = 0x02;
if( (myValue & (0x1 | 0x2)) == (0x1 | 0x2) ) {
    // both happened
}
else if( myValue & 0x1 ) {
    // left
}
else if( myValue & 0x2 ) {
    // right
}

// vs

bool leftButtonPressed = myValue & 0x01;
bool rightButtonPressed = myValue & 0x02;
if( leftButtonPressed && rightButtonPressed ) {
    // Read the line above like a sentence
}
else if( leftButtonPressed ) {
    // Read the line above like a sentence
}
else if( rightButtonPressed ) {
    // Read the line above like a sentence
}
----

Both examples avoid undefined behavior, allowing the compiler to optimize confidently. In the second example, boolean variables capture the results of bitwise operations, which may lead the compiler to optimize away these variables due to straightforward operations. Thus, the generated machine code may be similar or identical.
