= struct

.C
[source,c]
----
#include <stdio.h>

typedef struct Point {
    int x;
    int y;
} Point_t;

void point_move( point_t* const self, int deltaX, int deltaY ) {
    self->x += deltaX;
    self->y += deltaY;
}

void point_print( const point_t* const self ) {
    printf("(%d, %d)\r\n", self->x, self->y);
}

void foo(void) {
    Point_t a = { .x = 5, .y = 10 };
    point_move( &a, 2, 3 );
    point_print( &x );
}
----

.{cpp}
[source,c++]
----
#include <cstdio>

struct Point {
    int x;
    int y;
    Point( int x = 0, int y = 0 ) : x(x), y(y) {}
    void move( int deltaX, int deltaY ) {
        this->x += deltaX;
        this->y += deltaY;
    }
    void print() const {
        printf("(%d, %d)\r\n", this->x, this->y);
    }
};

void foo(){
    Point a( 5, 10 );
    a.move( 2, 3 );
    a.print();
}
----

== TL;DR
A `struct` in {cpp} is very similar to C, but they also include the ability to define member functions. Typical usage of a `struct` in {cpp} is when you have a simple aggregate type, that is a type whose only purpose is to contain related data.

== C
`struct` in C allows you to group related data into a single object with sequential memory layout. A `struct` is a contiguous block of memory, where each member occupies a defined amount of space, and the offset to access each member is calculated automatically by the compiler when you use the `.` or `+->+` operators.

=== Memory Layout
[source, c]
----
typedef struct Point {
    int x;
    int y;
} Point_t;

void foo(void) {
    Point_t p = { .x = 5, .y = 10 };
    int array[2];
    array[0] = p.x;
    array[1] = p.y;
}
----

In this example, `sizeof(p)` and `sizeof(array)` are equal because both are contiguous blocks of memory that contain two `int` elements. With the array, `array[0]` and `array[1]` correspond to the elements at offsets 0 and 1, respectively. The struct works similarly:

`p.x` can be thought of as `((unsigned char*)&p)` similar to `array[0]` +
`p.y` can be thought of as `+((unsigned char*)&p) + (sizeof(int))+` similar to `array[1]`

Thus, `struct` gives specific names and meaning to the elements of a collection, making code easier to read and maintain.

=== Padding
Padding is introduced by the compiler to ensure proper alignment of data members. For instance, on many systems, int values need to be aligned to a 4-byte boundary. This can cause "holes" in the memory layout where extra bytes are reserved but not used, making the struct larger than the sum of its members.

[source, c]
----
typedef struct Mixed {
    char c;
    int i;
} Mixed_t;
----

In this case, the `char c` will often be padded to align `int i` on a 4-byte boundary.

=== Related Functions
It's common to write functions that operate on `struct`'s, using the first parameter as a pointer to the struct instance. The pointer is often named `self`, `context`, `arg`, or something similar.

[source, c]
----
typedef struct Point {
    int x;
    int y;
} Point_t;

void point_move(Point_t* const self, int deltaX, int deltaY) {
    self->x = deltaX;
    self->y = deltaY;
}
----

Here, `self` is a pointer to the `struct Point` and allows modifying the values of `x` and `y`. The `const` on `self` ensures that the pointer itself cannot be changed to point elsewhere, but it allows modification of the data inside the `struct`.

Functions like `point_move` can operate on multiple instances of the same `struct` without being bound to one instance.

=== Member Access
In C, there is only public access to struct members. All members of a struct are visible and accessible to any code that includes the definition of the struct. However, various techniques can be used to hide the specific type of the struct and control access more effectively.

==== Using void* to Hide Type
In some cases, you may want to hide the specific type of a `struct` from users of your API. This can be achieved by using `void*` in function signatures instead of the concrete `struct` type. This technique provides a level of abstraction and allows changes to the underlying `struct` type without affecting the API.

[source, c]
----
typedef struct Point {
    int x;
    int y;
} Point_t;

void point_move(void* const self, int deltaX, int deltaY) {
    Point_t* const p = (Point_t* const)self;
    p->x += deltaX;
    p->y += deltaY;
}
----

In this example, `point_move` takes a `void*` parameter and casts it to the appropriate `struct` type within the function. This approach hides the specific implementation of the `struct` from the function's users, who only need to know that they should pass a pointer to some opaque data.

==== Forward Declarations

Another common practice to hide the details of a `struct` is to use forward declarations in header files. You declare the `struct` in the header file but define it only in the corresponding source file. This approach keeps the implementation details hidden from users and provides a clean interface.

[source, c]
----
/* point.h */
typedef struct Point Point_t; // Forward declaration

void point_move(Point_t* const self, int deltaX, int deltaY);
void point_print(const Point_t* const self);
----
[source, c]
----
/* point.c */
#include "point.h"
#include <stdio.h>

struct Point { int x; int y; }; // define type

void point_move(Point_t* const self, int deltaX, int deltaY) {
    self->x += deltaX;
    self->y += deltaY;
}

void point_print(const Point_t* const self) {
    printf("(%d, %d)\r\n", self->x, self->y);
}
----
In this example, the struct definition is hidden in the source file (point.c), while the header file (point.h) only contains a forward declaration of the struct and the function prototypes. This encapsulation hides implementation details and promotes modularity.

== {cpp}

=== Memory Layout
The memory layout of `struct` in {cpp} is the same as in C. Members are stored in contiguous memory locations, and the compiler calculates the offsets for each member automatically. If the `struct` contains members of different types, padding might be introduced to align data members to word boundaries for performance reasons.

[source, cpp]
----
#include <cstdio>

struct Mixed {
    char c;
    int i;
};

int main() {
    printf("%u\r\n", sizeof(Mixed)); // Output may include padding
}
----
In this example, `sizeof(Mixed)` may be larger than the sum of the sizes of `char` and `int` due to padding. `char c` is often aligned at the start, while `int i` may be padded to align with a 4-byte boundary.

=== Member Function
In {cpp}, `struct` members can include functions. This is different from C, where `struct`s can only contain data. The first parameter of these member functions is an implicit `this` pointer, which refers to the instance of the struct the function is operating on.

NOTE: member functions do not add to the memory footprint of a `struct`

[source, cpp]
----
#include <cstdio>

// C++
struct Point {
    int x;
    int y;
    Point( int x = 0, int y = 0 ) : x(x), y(y) {}
    void move( int deltaX, int deltaY ) {
        this->x += deltaX;
        this->y += deltaY;
    }
    void print() const {
        printf("(%d, %d)\r\n", this->x, this->y);
    }
};

// C
typedef struct Point {
    int x;
    int y;
} Point_t;

void point_move( point_t* const self, int deltaX, int deltaY ) {
    self->x += deltaX;
    self->y += deltaY;
}

void point_print( const point_t* const self ) {
    printf("(%d, %d)\r\n", self->x, self->y);
}

// Comparison
int main() {
    Point p1( 5, 10 );
    p1.move( 2, 3 ); // &p1 is the `this` pointer for this call to move()
    p1.print();      // &p1 is the `this` pointer for this call to print()

    Point_t p2 = { 5, 10 };
    point_move( &p2, 2, 3 );
    point_print( &p2 );
}
----
Here, `move` and `print` are member functions of `struct` `Point`. The `this` pointer is automatically passed to these functions, allowing them to access and modify the members of `Point`.

Moving the C code around until it looks like the {cpp} example

. `point_move( &p2, 2, 3 );` - original C version
. `+(&p2)->point_move( 2, 3 );+` - moving `self` aka `this` to the left operand of `+->+`
. `p2.point_move(2, 3);` - using the `.` operator instead on `this`
. `p2.move(2, 3);` - rename the function as repeating the type name is redundant, as `move` can only be called on `Point` objects.

NOTE: The type of `self` in `point_move` is a constant pointer to a mutable `Point_t`. This reflects the type of `this` in a `non-const` member function.

NOTE: The type of `self` in `point_print` is a constant pointer to a constant `Point_t`. This reflects the type of `this` in a `const` member function.

NOTE: In the {cpp} example, `move()` is not required to explicitly use `this+->+`, it's more common to **__not__** explicitly use `this` directly unless there is a naming conflict between a data member and a member function parameter.

=== Static Member Data and Functions
Static data members have a single instance per type, no matter how many type instances there are. Static member functions do not receive the this pointer and are not associated with any particular instance of the struct. They can be called using the scope resolution operator `::` and can only access static members of the struct.

[source,c++]
----
// S.hpp
struct S {
    static int counter;
    static void increment() { ++counter; }
};

// S.cpp
#include <cstdio>

int S::counter = 0; // this is where the static member of S lives

void example() {
    S::increment(); // no instance of S required
    S myValue;
    myValue.increment(); // Can also call static functions with object instance
    printf("counter: %d\r\n", S::counter); // access the static member directly
}
----

=== Member Access
Members declared as `public` are accessible from any code that can see the definition of the `struct`. This is the default access specifier for `struct` members.

[source, cpp]
----
struct PublicExample {
    int value; // public by default
};

int main() {
    PublicExample e;
    e.value = 42; // Accessible directly
}
----
In this example, `value` is a public member and can be accessed directly from outside the struct.

==== protected
Members declared as `protected` can only be accessed by the `struct` itself, and by derived `struct`s. They are not accessible from outside the `struct`.

[source, cpp]
----
struct Base {
protected:
    int value;
};

struct Derived : Base {
    void updateValue(int v) {
        value = v; // Accessible within derived class
    }
};

int main() {
    Derived d;
    d.updateValue(42); // OK
}
----
In this example, `value` is a protected data member and is accessible within `Derived`, but not from outside the `struct`.

==== private
Members declared as `private` can only be accessed by the `struct` itself. They are not accessible from derived classes or from outside the struct.

[source, cpp]
----
#include <cstdio>

struct PrivateExample {
private:
    int value;
public:
    void setValue(int v) {
        value = v;
    }
    int getValue() const {
        return value;
    }
};

int main() {
    PrivateExample e;
    e.setValue(42); // OK
    printf("%d\r\n", e.getValue()); // OK
}
----
In this example, `value` is a private member and can only be accessed through the public member functions `setValue` and `getValue`.

