= Variable Declarations

[source,c,indent=0]
----
void c89(void) {
    int len;
    int i;
    int noLongerNeedI;
    len = 5;
    for( i = 0; i < len; i++ ) {
        /* ... */
    }
    /* Could've reused the space reserved for i */
    noLongerNeedI = len + 10;
}
----
VS
[source,c++,indent=0]
----
void modern() {
    int len = 5;
    for( int i = 0; i < len; i++ ) {
        // ...
    }
    int reusedMemoryNoLongerNeededForI = len + 10; // most likely
}
----

== TL;DR
There's no benefit to sticking with C89-style variable declaration in {cpp}.

Modern C and {cpp} best practices favor declaring variables as close to their point of use as possible. This shift from older practices, similar to the move away from xref:implicit_int_return.adoc[implicit return types], helps to improve memory efficiency, narrow scope, localize behaviors, etc...

== What?
In C89, variables **must** be declared at the beginning of a block, before any other statements.

Starting with C99 and continuing into all versions of {cpp}, variables can be declared anywhere within a block.

== Why?
. Declaring and initializing variables close to their usage ensures they start with a known value, minimizing bugs from uninitialized variables.
. Declaring variables near their point of use helps the compiler with optimizations like link:https://en.cppreference.com/w/cpp/language/copy_elision[return value optimization], especially with large objects. Example: +
`Data data = parseData();` +
. Limiting variable scope avoids wasting stack space on variables not needed throughout the block. Example: +
`for( int i = 0; i < 5; ++i ) {}` +
`i` only exists within the loop scope, freeing its memory immediately after.

Modern practices enhance memory management and code maintainability by confining variable lifetimes to their necessary scopes.

== List Initialization
{cpp} supports list initialization for variables, offering:

* **Consistent Syntax**: The `{}` syntax is uniform across simple variables, arrays, structs, and user-defined types, promoting consistency in code.

* **Narrowing Conversion Prevention**: List initialization prevents implicit narrowing conversions, where a larger data type might be truncated when assigned to a smaller data type, reducing potential bugs. Braces ensure the compiler flags such conversions.

[source,c++]
----
int a{5};         // same as int a = 5;
double b{4.5};    // same as double b = 4.5;
float c{4.5};     // Narrowing conversion allowed since 4.5 fits in a float

// Prevents narrowing conversion
int d{4.5};       // Error: cannot convert double to int
float e{1e40};    // Error: overflow: cannot convert large double to float

int arr[3]{1, 2, 3};  // List initialization for arrays

struct Point {
    int x;
    int y;
};

Point p{10, 20};  // List initialization for structs
----

== Designated Initializers For Aggregate Types
While {cpp} does not support designated initializers in the same way as C, {cpp}20 introduces them for aggregate initialization with link:https://en.cppreference.com/w/cpp/language/aggregate_initialization[aggregate types].

.Example
[source,c++]
----
struct Point {
    int x;
    int y;
};

// Designated initialization in C++20
Point p{.x = 10, .y = 20};
----
